language: scala
sudo: false

scala:
  - 2.10.4
  - 2.11.5

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION update

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
